addSbtPlugin("com.github.sbt"      % "sbt-pgp"            % "2.2.1")
addSbtPlugin("org.xerial.sbt"      % "sbt-sonatype"       % "3.11.2")
addSbtPlugin("org.scalameta"       % "sbt-scalafmt"       % "2.5.2")
addSbtPlugin("org.scalameta"       % "sbt-mdoc"           % "2.6.4")
addSbtPlugin("org.jetbrains.scala" % "sbt-ide-settings"   % "1.1.2")
addSbtPlugin("org.typelevel"       % "sbt-typelevel"      % "0.7.7")
addSbtPlugin("org.typelevel"       % "sbt-typelevel-site" % "0.7.7")
